# Generated by Django 3.1.5 on 2021-01-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_airports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='returning_date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='travel_class',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrAirport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrAirport', to='booking.airports'),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrCity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrHour',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='deptAirport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deptAirport', to='booking.airports'),
        ),
        migrations.AddField(
            model_name='flight',
            name='deptCity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='deptHour',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DateTimeField(null=True),
        ),
    ]
