# Generated by Django 3.1.5 on 2021-01-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210119_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrAirport',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='deptAirport',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Airports',
        ),
    ]
